services:
    documentserver:
        image: onlyoffice/documentserver-ee
        volumes:
            - /opt/onlyoffice/Data:/var/www/onlyoffice/Data
        ports:
            - "8008:80"
        environment:
            - JWT_ENABLED=false
            - ALLOW_PRIVATE_IP_ADDRESS=true
    example:
        build: .
        ports:
            - "80:80"
