version: "3.7"
services:
    documentserver:
        image: onlyoffice/documentserver-ee
        volumes:
            - /opt/onlyoffice/Data:/var/www/onlyoffice/Data
        ports:
            - "8008:80"
    ds-test-example:
        build: .
        ports:
            - "80:80"
